#!/usr/bin/env bash
# Verum Installer for Linux and macOS
# Usage: bash install/install.sh
# Or:    curl -fsSL <url>/install.sh | bash

set -euo pipefail

KRAUM_HOME="${HOME}/.verum"
VERUM_BIN="${KRAUM_HOME}/bin"
SYMLINK_DIR="/usr/local/bin"
REPO_URL="https://github.com/jeffmillr/verum.git"
MIN_NODE_VERSION=18

# ---------- helpers ----------

info()  { printf "\033[1;34m[verum]\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m[verum]\033[0m %s\n" "$*"; }
error() { printf "\033[1;31m[verum]\033[0m %s\n" "$*" >&2; }
die()   { error "$@"; exit 1; }

confirm() {
  local prompt="${1:-Continue?} [y/N] "
  read -r -p "$prompt" answer
  [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]
}

# ---------- preflight ----------

detect_os() {
  case "$(uname -s)" in
    Linux*)  OS="linux"  ;;
    Darwin*) OS="macos"  ;;
    *)       die "Unsupported operating system: $(uname -s)" ;;
  esac
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64)  ARCH="x64"   ;;
    aarch64|arm64) ARCH="arm64" ;;
    *)             die "Unsupported architecture: $(uname -m)" ;;
  esac
}

check_node() {
  if ! command -v node &>/dev/null; then
    die "Node.js is not installed. Install Node.js ${MIN_NODE_VERSION}+ from https://nodejs.org and try again."
  fi

  local node_major
  node_major="$(node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))')"
  if (( node_major < MIN_NODE_VERSION )); then
    die "Node.js ${MIN_NODE_VERSION}+ required (found v${node_major}). Please upgrade: https://nodejs.org"
  fi
  info "Node.js v$(node --version | tr -d 'v') detected"
}

check_npm() {
  if ! command -v npm &>/dev/null; then
    die "npm is not installed. It usually ships with Node.js — reinstall Node.js from https://nodejs.org"
  fi
  info "npm v$(npm --version) detected"
}

# ---------- install ----------

install_source() {
  if [[ -f "package.json" ]] && grep -q '"name": "verum"' package.json 2>/dev/null; then
    info "Running inside a Verum checkout — using current directory as source"
    SOURCE_DIR="$(pwd)"
  else
    SOURCE_DIR=""
  fi

  if [[ -d "${KRAUM_HOME}" ]]; then
    warn "Existing installation found at ${KRAUM_HOME}"
    if confirm "Remove and reinstall?"; then
      rm -rf "${KRAUM_HOME}"
    else
      die "Installation aborted."
    fi
  fi

  mkdir -p "${KRAUM_HOME}"

  if [[ -n "${SOURCE_DIR}" ]]; then
    info "Copying project files to ${KRAUM_HOME}..."
    # Copy everything except node_modules and dist
    rsync -a --exclude='node_modules' --exclude='dist' "${SOURCE_DIR}/" "${KRAUM_HOME}/" 2>/dev/null \
      || (cd "${SOURCE_DIR}" && tar --exclude='node_modules' --exclude='dist' -cf - . | tar -xf - -C "${KRAUM_HOME}")
  else
    if command -v git &>/dev/null; then
      info "Cloning Verum repository..."
      git clone --depth 1 "${REPO_URL}" "${KRAUM_HOME}" \
        || die "Failed to clone repository. Check your network or clone manually to ~/.verum"
    else
      die "git is not installed and you are not inside a Verum checkout. Install git or run this script from the repo root."
    fi
  fi
}

install_deps() {
  info "Installing production dependencies..."
  cd "${KRAUM_HOME}"
  npm install --production || die "npm install failed"
}

build_project() {
  info "Building TypeScript..."
  cd "${KRAUM_HOME}"
  # Need dev deps for tsc; install all, build, then prune
  npm install || die "npm install (full) failed"
  npx tsc -p tsconfig.json || die "TypeScript build failed"
  info "Build successful"
}

create_wrapper() {
  mkdir -p "${VERUM_BIN}"

  local node_bin
  node_bin="$(command -v node)"

  cat > "${VERUM_BIN}/verum" <<WRAPPER
#!/usr/bin/env bash
# Verum CLI wrapper — generated by install.sh
exec "${node_bin}" "${KRAUM_HOME}/dist/engine/cli.js" "\$@"
WRAPPER

  chmod +x "${VERUM_BIN}/verum"
  info "Wrapper script created at ${VERUM_BIN}/verum"
}

create_symlink() {
  if [[ -w "${SYMLINK_DIR}" ]]; then
    ln -sf "${VERUM_BIN}/verum" "${SYMLINK_DIR}/verum"
    info "Symlink created: ${SYMLINK_DIR}/verum"
  else
    info "Creating symlink in ${SYMLINK_DIR} requires elevated privileges"
    if confirm "Use sudo to create symlink?"; then
      sudo ln -sf "${VERUM_BIN}/verum" "${SYMLINK_DIR}/verum"
      info "Symlink created: ${SYMLINK_DIR}/verum"
    else
      warn "Skipped symlink. Add ${VERUM_BIN} to your PATH manually:"
      warn "  export PATH=\"${VERUM_BIN}:\$PATH\""
    fi
  fi
}

# ---------- service (Linux systemd) ----------

install_systemd_service() {
  if [[ "${OS}" != "linux" ]]; then return; fi
  if ! command -v systemctl &>/dev/null; then
    warn "systemd not found — skipping service installation"
    return
  fi

  echo ""
  info "Verum includes a web UI that can run as a background service."
  if ! confirm "Install systemd service for the Verum web UI?"; then
    return
  fi

  local node_bin node_dir service_file
  node_bin="$(command -v node)"
  node_dir="$(dirname "${node_bin}")"
  service_file="/etc/systemd/system/verum-web.service"

  local template="${KRAUM_HOME}/install/verum-web.service"
  if [[ ! -f "${template}" ]]; then
    warn "Service template not found at ${template} — skipping"
    return
  fi

  local rendered
  rendered="$(sed \
    -e "s|%USER%|${USER}|g" \
    -e "s|%INSTALL_DIR%|${KRAUM_HOME}|g" \
    -e "s|%NODE_DIR%|${node_dir}|g" \
    -e "s|%NODE_BIN%|${node_bin}|g" \
    "${template}")"

  echo "${rendered}" | sudo tee "${service_file}" >/dev/null
  sudo systemctl daemon-reload
  sudo systemctl enable verum-web.service
  info "systemd service installed and enabled"
  info "Start it with: sudo systemctl start verum-web"
}

# ---------- service (macOS launchd) ----------

install_launchd_plist() {
  if [[ "${OS}" != "macos" ]]; then return; fi

  echo ""
  info "Verum includes a web UI that can run as a background service."
  if ! confirm "Install launchd service for the Verum web UI?"; then
    return
  fi

  local node_bin plist_dest
  node_bin="$(command -v node)"
  plist_dest="${HOME}/Library/LaunchAgents/com.verum.web.plist"

  local template="${KRAUM_HOME}/install/com.verum.web.plist"
  if [[ ! -f "${template}" ]]; then
    warn "Plist template not found at ${template} — skipping"
    return
  fi

  mkdir -p "${HOME}/Library/LaunchAgents"

  sed \
    -e "s|%NODE_BIN%|${node_bin}|g" \
    -e "s|%INSTALL_DIR%|${KRAUM_HOME}|g" \
    "${template}" > "${plist_dest}"

  launchctl load "${plist_dest}" 2>/dev/null || true
  info "launchd plist installed at ${plist_dest}"
  info "The web UI will start automatically on login"
  info "Start now with: launchctl start com.verum.web"
}

# ---------- main ----------

main() {
  echo ""
  echo "  ╔═══════════════════════════════════════╗"
  echo "  ║   Verum Installer                   ║"
  echo "  ║   Adversarial Validation Framework    ║"
  echo "  ╚═══════════════════════════════════════╝"
  echo ""

  detect_os
  detect_arch
  info "Detected: ${OS} / ${ARCH}"

  check_node
  check_npm

  install_source
  build_project
  create_wrapper
  create_symlink

  install_systemd_service
  install_launchd_plist

  echo ""
  info "============================================"
  info "  Verum installed successfully!"
  info "============================================"
  echo ""
  info "Next steps:"
  info "  verum list          — list available tests"
  info "  verum suite all     — run all test suites"
  info "  verum report summary — view latest report"
  echo ""
  info "Web UI:  verum web  (or start the service)"
  info "Docs:    ${KRAUM_HOME}/docs/"
  info "Uninstall: bash ${KRAUM_HOME}/install/uninstall.sh"
  echo ""
}

main "$@"
