#!/usr/bin/env bash
# Krakzen Installer for Linux and macOS
# Usage: bash install/install.sh
# Or:    curl -fsSL <url>/install.sh | bash

set -euo pipefail

KRAKZEN_HOME="${HOME}/.krakzen"
KRAKZEN_BIN="${KRAKZEN_HOME}/bin"
SYMLINK_DIR="/usr/local/bin"
REPO_URL="https://github.com/jeffmillr/krakzen.git"
MIN_NODE_VERSION=18

# ---------- helpers ----------

info()  { printf "\033[1;34m[krakzen]\033[0m %s\n" "$*"; }
warn()  { printf "\033[1;33m[krakzen]\033[0m %s\n" "$*"; }
error() { printf "\033[1;31m[krakzen]\033[0m %s\n" "$*" >&2; }
die()   { error "$@"; exit 1; }

confirm() {
  local prompt="${1:-Continue?} [y/N] "
  read -r -p "$prompt" answer
  [[ "${answer,,}" == "y" || "${answer,,}" == "yes" ]]
}

# ---------- preflight ----------

detect_os() {
  case "$(uname -s)" in
    Linux*)  OS="linux"  ;;
    Darwin*) OS="macos"  ;;
    *)       die "Unsupported operating system: $(uname -s)" ;;
  esac
}

detect_arch() {
  case "$(uname -m)" in
    x86_64|amd64)  ARCH="x64"   ;;
    aarch64|arm64) ARCH="arm64" ;;
    *)             die "Unsupported architecture: $(uname -m)" ;;
  esac
}

check_node() {
  if ! command -v node &>/dev/null; then
    die "Node.js is not installed. Install Node.js ${MIN_NODE_VERSION}+ from https://nodejs.org and try again."
  fi

  local node_major
  node_major="$(node -e 'process.stdout.write(String(process.versions.node.split(".")[0]))')"
  if (( node_major < MIN_NODE_VERSION )); then
    die "Node.js ${MIN_NODE_VERSION}+ required (found v${node_major}). Please upgrade: https://nodejs.org"
  fi
  info "Node.js v$(node --version | tr -d 'v') detected"
}

check_npm() {
  if ! command -v npm &>/dev/null; then
    die "npm is not installed. It usually ships with Node.js — reinstall Node.js from https://nodejs.org"
  fi
  info "npm v$(npm --version) detected"
}

# ---------- install ----------

install_source() {
  if [[ -f "package.json" ]] && grep -q '"name": "krakzen"' package.json 2>/dev/null; then
    info "Running inside a Krakzen checkout — using current directory as source"
    SOURCE_DIR="$(pwd)"
  else
    SOURCE_DIR=""
  fi

  if [[ -d "${KRAKZEN_HOME}" ]]; then
    warn "Existing installation found at ${KRAKZEN_HOME}"
    if confirm "Remove and reinstall?"; then
      rm -rf "${KRAKZEN_HOME}"
    else
      die "Installation aborted."
    fi
  fi

  mkdir -p "${KRAKZEN_HOME}"

  if [[ -n "${SOURCE_DIR}" ]]; then
    info "Copying project files to ${KRAKZEN_HOME}..."
    # Copy everything except node_modules and dist
    rsync -a --exclude='node_modules' --exclude='dist' "${SOURCE_DIR}/" "${KRAKZEN_HOME}/" 2>/dev/null \
      || (cd "${SOURCE_DIR}" && tar --exclude='node_modules' --exclude='dist' -cf - . | tar -xf - -C "${KRAKZEN_HOME}")
  else
    if command -v git &>/dev/null; then
      info "Cloning Krakzen repository..."
      git clone --depth 1 "${REPO_URL}" "${KRAKZEN_HOME}" \
        || die "Failed to clone repository. Check your network or clone manually to ~/.krakzen"
    else
      die "git is not installed and you are not inside a Krakzen checkout. Install git or run this script from the repo root."
    fi
  fi
}

install_deps() {
  info "Installing production dependencies..."
  cd "${KRAKZEN_HOME}"
  npm install --production || die "npm install failed"
}

build_project() {
  info "Building TypeScript..."
  cd "${KRAKZEN_HOME}"
  # Need dev deps for tsc; install all, build, then prune
  npm install || die "npm install (full) failed"
  npx tsc -p tsconfig.json || die "TypeScript build failed"
  info "Build successful"
}

create_wrapper() {
  mkdir -p "${KRAKZEN_BIN}"

  local node_bin
  node_bin="$(command -v node)"

  cat > "${KRAKZEN_BIN}/krakzen" <<WRAPPER
#!/usr/bin/env bash
# Krakzen CLI wrapper — generated by install.sh
exec "${node_bin}" "${KRAKZEN_HOME}/dist/engine/cli.js" "\$@"
WRAPPER

  chmod +x "${KRAKZEN_BIN}/krakzen"
  info "Wrapper script created at ${KRAKZEN_BIN}/krakzen"
}

create_symlink() {
  if [[ -w "${SYMLINK_DIR}" ]]; then
    ln -sf "${KRAKZEN_BIN}/krakzen" "${SYMLINK_DIR}/krakzen"
    info "Symlink created: ${SYMLINK_DIR}/krakzen"
  else
    info "Creating symlink in ${SYMLINK_DIR} requires elevated privileges"
    if confirm "Use sudo to create symlink?"; then
      sudo ln -sf "${KRAKZEN_BIN}/krakzen" "${SYMLINK_DIR}/krakzen"
      info "Symlink created: ${SYMLINK_DIR}/krakzen"
    else
      warn "Skipped symlink. Add ${KRAKZEN_BIN} to your PATH manually:"
      warn "  export PATH=\"${KRAKZEN_BIN}:\$PATH\""
    fi
  fi
}

# ---------- service (Linux systemd) ----------

install_systemd_service() {
  if [[ "${OS}" != "linux" ]]; then return; fi
  if ! command -v systemctl &>/dev/null; then
    warn "systemd not found — skipping service installation"
    return
  fi

  echo ""
  info "Krakzen includes a web UI that can run as a background service."
  if ! confirm "Install systemd service for the Krakzen web UI?"; then
    return
  fi

  local node_bin node_dir service_file
  node_bin="$(command -v node)"
  node_dir="$(dirname "${node_bin}")"
  service_file="/etc/systemd/system/krakzen-web.service"

  local template="${KRAKZEN_HOME}/install/krakzen-web.service"
  if [[ ! -f "${template}" ]]; then
    warn "Service template not found at ${template} — skipping"
    return
  fi

  local rendered
  rendered="$(sed \
    -e "s|%USER%|${USER}|g" \
    -e "s|%INSTALL_DIR%|${KRAKZEN_HOME}|g" \
    -e "s|%NODE_DIR%|${node_dir}|g" \
    -e "s|%NODE_BIN%|${node_bin}|g" \
    "${template}")"

  echo "${rendered}" | sudo tee "${service_file}" >/dev/null
  sudo systemctl daemon-reload
  sudo systemctl enable krakzen-web.service
  info "systemd service installed and enabled"
  info "Start it with: sudo systemctl start krakzen-web"
}

# ---------- service (macOS launchd) ----------

install_launchd_plist() {
  if [[ "${OS}" != "macos" ]]; then return; fi

  echo ""
  info "Krakzen includes a web UI that can run as a background service."
  if ! confirm "Install launchd service for the Krakzen web UI?"; then
    return
  fi

  local node_bin plist_dest
  node_bin="$(command -v node)"
  plist_dest="${HOME}/Library/LaunchAgents/com.krakzen.web.plist"

  local template="${KRAKZEN_HOME}/install/com.krakzen.web.plist"
  if [[ ! -f "${template}" ]]; then
    warn "Plist template not found at ${template} — skipping"
    return
  fi

  mkdir -p "${HOME}/Library/LaunchAgents"

  sed \
    -e "s|%NODE_BIN%|${node_bin}|g" \
    -e "s|%INSTALL_DIR%|${KRAKZEN_HOME}|g" \
    "${template}" > "${plist_dest}"

  launchctl load "${plist_dest}" 2>/dev/null || true
  info "launchd plist installed at ${plist_dest}"
  info "The web UI will start automatically on login"
  info "Start now with: launchctl start com.krakzen.web"
}

# ---------- main ----------

main() {
  echo ""
  echo "  ╔═══════════════════════════════════════╗"
  echo "  ║   Krakzen Installer                   ║"
  echo "  ║   Adversarial Validation Framework    ║"
  echo "  ╚═══════════════════════════════════════╝"
  echo ""

  detect_os
  detect_arch
  info "Detected: ${OS} / ${ARCH}"

  check_node
  check_npm

  install_source
  build_project
  create_wrapper
  create_symlink

  install_systemd_service
  install_launchd_plist

  echo ""
  info "============================================"
  info "  Krakzen installed successfully!"
  info "============================================"
  echo ""
  info "Next steps:"
  info "  krakzen list          — list available tests"
  info "  krakzen suite all     — run all test suites"
  info "  krakzen report summary — view latest report"
  echo ""
  info "Web UI:  krakzen web  (or start the service)"
  info "Docs:    ${KRAKZEN_HOME}/docs/"
  info "Uninstall: bash ${KRAKZEN_HOME}/install/uninstall.sh"
  echo ""
}

main "$@"
